# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('masterorderid', models.BigIntegerField(db_column='MasterOrderID')),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, db_column='Amount', null=True, max_digits=18)),
                ('lastamount', models.DecimalField(blank=True, decimal_places=0, db_column='LastAmount', null=True, max_digits=18)),
                ('commitrq', models.CharField(blank=True, db_column='CommitRQ', max_length=2000)),
                ('eid', models.CharField(blank=True, db_column='EID', max_length=20)),
                ('salemode', models.SmallIntegerField(blank=True, db_column='SaleMode', null=True)),
                ('destcity', models.IntegerField(blank=True, db_column='DestCity', null=True)),
                ('departurecity', models.IntegerField(blank=True, db_column='DepartureCity', null=True)),
                ('salescity', models.IntegerField(blank=True, db_column='SalesCity', null=True)),
                ('vipgrade', models.IntegerField(blank=True, db_column='VipGrade', null=True)),
                ('serverfromtype', models.IntegerField(blank=True, db_column='ServerFromType', null=True)),
                ('uid', models.CharField(blank=True, db_column='UID', max_length=20)),
                ('productid', models.IntegerField(blank=True, db_column='ProductID', null=True)),
                ('isintl', models.SmallIntegerField(blank=True, db_column='IsIntl', null=True)),
                ('diytype', models.SmallIntegerField(blank=True, db_column='DIYType', null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.CharField(blank=True, db_column='EndDate', max_length=50)),
                ('datachange_lasttime', models.DateTimeField(blank=True, db_column='DataChange_LastTime', null=True)),
                ('shoppingid', models.BigIntegerField(blank=True, db_column='ShoppingID', null=True)),
                ('newshoppingid', models.CharField(blank=True, db_column='NewShoppingID', max_length=50)),
                ('datacreate_lasttime', models.DateTimeField(db_column='DataCreate_LastTime')),
            ],
            options={
                'db_table': 'DIY_Commit',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CommitOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, verbose_name='ID', serialize=False)),
                ('masterorderid', models.BigIntegerField(db_column='MasterOrderID')),
                ('status', models.SmallIntegerField(db_column='Status')),
                ('amount', models.DecimalField(decimal_places=0, db_column='Amount', max_digits=18)),
                ('lastamount', models.DecimalField(decimal_places=0, db_column='LastAmount', max_digits=18)),
                ('masterorderinfo', models.CharField(blank=True, db_column='MasterOrderInfo', max_length=2000)),
                ('eid', models.CharField(blank=True, db_column='EID', max_length=20)),
                ('salemode', models.SmallIntegerField(blank=True, db_column='SaleMode', null=True)),
                ('destcity', models.IntegerField(blank=True, db_column='DestCity', null=True)),
                ('departurecity', models.IntegerField(blank=True, db_column='DepartureCity', null=True)),
                ('salescity', models.IntegerField(blank=True, db_column='SalesCity', null=True)),
                ('vipgrade', models.IntegerField(blank=True, db_column='VipGrade', null=True)),
                ('serverfromurl', models.CharField(blank=True, db_column='ServerFromUrl', max_length=255)),
                ('uid', models.CharField(blank=True, db_column='UID', max_length=20)),
                ('productid', models.IntegerField(blank=True, db_column='ProductID', null=True)),
                ('isintl', models.SmallIntegerField(blank=True, db_column='IsIntl', null=True)),
                ('diytype', models.SmallIntegerField(blank=True, db_column='DIYType', null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('shoppingid', models.BigIntegerField(blank=True, db_column='ShoppingID', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('datachange_lasttime', models.DateTimeField(blank=True, db_column='DataChange_LastTime', null=True)),
                ('newshoppingid', models.CharField(blank=True, db_column='NewShoppingID', max_length=50)),
                ('datacreate_lasttime', models.DateTimeField(db_column='DataCreate_LastTime')),
            ],
            options={
                'db_table': 'DIY_Commit',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DiyOrderRealtime',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('diy_orderid', models.BigIntegerField(blank=True, db_column='DIY_OrderID', null=True)),
                ('packageid', models.IntegerField(blank=True, db_column='PackageID', null=True)),
                ('packagetitle', models.CharField(blank=True, db_column='PackageTitle', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, db_column='Amount', null=True, max_digits=19)),
                ('currentamount', models.DecimalField(blank=True, decimal_places=4, db_column='CurrentAmount', null=True, max_digits=19)),
                ('priceadjust', models.DecimalField(blank=True, decimal_places=4, db_column='PriceAdjust', null=True, max_digits=19)),
                ('orderdate', models.DateTimeField(blank=True, db_column='OrderDate', null=True)),
                ('diy_startdate', models.DateTimeField(blank=True, db_column='DIY_StartDate', null=True)),
                ('diy_enddate', models.DateTimeField(blank=True, db_column='DIY_EndDate', null=True)),
                ('uid', models.CharField(blank=True, db_column='UID', max_length=20)),
                ('ctripcardno', models.CharField(blank=True, db_column='CtripCardNo', max_length=20)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('isintl', models.SmallIntegerField(blank=True, db_column='IsIntl', null=True)),
                ('journeytype', models.SmallIntegerField(blank=True, db_column='JourneyType', null=True)),
                ('diytype', models.SmallIntegerField(blank=True, db_column='DIYType', null=True)),
                ('bookrq', models.TextField(blank=True, db_column='BookRQ')),
                ('bookrs', models.TextField(blank=True, db_column='BookRS')),
                ('serverfrom', models.CharField(blank=True, db_column='ServerFrom', max_length=100)),
                ('vipgrade', models.IntegerField(blank=True, db_column='VipGrade', null=True)),
                ('isonline', models.NullBooleanField(db_column='IsOnline')),
                ('salescity', models.IntegerField(blank=True, db_column='SalesCity', null=True)),
                ('processoper', models.CharField(blank=True, db_column='ProcessOper', max_length=20)),
                ('cancelreason', models.CharField(blank=True, db_column='CancelReason', max_length=400)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=500)),
                ('confirmclienttime', models.DateTimeField(blank=True, db_column='ConfirmClientTime', null=True)),
                ('tmoney', models.DecimalField(blank=True, decimal_places=4, db_column='TMoney', null=True, max_digits=19)),
                ('emoney', models.DecimalField(blank=True, decimal_places=4, db_column='EMoney', null=True, max_digits=19)),
                ('payablepay', models.DecimalField(blank=True, decimal_places=4, db_column='PayablePay', null=True, max_digits=19)),
                ('payfinished', models.CharField(blank=True, db_column='PayFinished', max_length=1)),
                ('realget', models.DecimalField(blank=True, decimal_places=4, db_column='RealGet', null=True, max_digits=19)),
                ('ems_number', models.CharField(blank=True, db_column='EMS_Number', max_length=50)),
                ('datachange_lasttime', models.DateTimeField(blank=True, db_column='DataChange_LastTime', null=True)),
                ('serverfromtype', models.IntegerField(blank=True, db_column='ServerFromType', null=True)),
                ('startcity', models.IntegerField(blank=True, db_column='StartCity', null=True)),
                ('destcity', models.IntegerField(blank=True, db_column='DestCity', null=True)),
                ('provconfirmintervaltime', models.IntegerField(blank=True, db_column='ProvConfirmIntervalTime', null=True)),
                ('allianceid', models.IntegerField(blank=True, db_column='AllianceID', null=True)),
                ('sid', models.CharField(blank=True, db_column='SID', max_length=100)),
                ('ouid', models.CharField(blank=True, db_column='OUID', max_length=100)),
                ('manualflag', models.SmallIntegerField(blank=True, db_column='ManualFlag', null=True)),
                ('businessmgr', models.CharField(blank=True, db_column='BusinessMgr', max_length=50)),
                ('processstatus', models.IntegerField(blank=True, db_column='ProcessStatus', null=True)),
                ('personnum', models.IntegerField(blank=True, db_column='PersonNum', null=True)),
                ('salemode', models.IntegerField(blank=True, db_column='SaleMode', null=True)),
                ('eid', models.CharField(blank=True, db_column='EID', max_length=20)),
                ('oprationnote', models.CharField(blank=True, db_column='OprationNote', max_length=5000)),
                ('isgivettdcoupon', models.NullBooleanField(db_column='IsGiveTTDCoupon')),
                ('productsalemode', models.IntegerField(blank=True, db_column='ProductSaleMode', null=True)),
                ('orderpolicycode', models.SmallIntegerField(blank=True, db_column='OrderPolicyCode', null=True)),
                ('datacreate_lasttime', models.DateTimeField(db_column='DataCreate_LastTime')),
            ],
            options={
                'db_table': 'DIY_Order',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DiyPageviewStatisticRealtime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pageid', models.IntegerField(blank=True, null=True)),
                ('statistic_date', models.DateField(blank=True, null=True)),
                ('pv', models.IntegerField(blank=True, null=True)),
                ('uv', models.IntegerField(blank=True, null=True)),
                ('datachange_lasttime', models.DateTimeField(db_column='DataChange_LastTime')),
            ],
            options={
                'db_table': 'diy_pageview_statistic_realtime',
                'managed': False,
            },
            bases=(models.Model,),
        ),
    ]
